# Generated by Django 3.1.1 on 2020-10-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='field',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='movies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='socialMedia',
            field=models.TextField(blank=True),
        ),
    ]
