# Generated by Django 3.1.1 on 2020-10-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201014_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailer',
            old_name='links',
            new_name='short',
        ),
    ]
