# Generated by Django 3.1.1 on 2020-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_movie_contentheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='contentHeader',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
