# Generated by Django 3.1.1 on 2020-10-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_movie_contentheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ch',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
