# Generated by Django 3.1.1 on 2020-10-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_movie_ch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='youtubeLink',
            field=models.TextField(blank=True),
        ),
    ]
