# Generated by Django 3.1.1 on 2020-10-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_trailer_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
