# Generated by Django 3.1.1 on 2020-10-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articalimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticalImage',
        ),
    ]
