# Generated by Django 3.1.1 on 2020-10-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201002_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='contentHeader',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
