# Generated by Django 3.1.1 on 2020-11-02 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='webSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('director', models.CharField(max_length=120)),
                ('cast', models.TextField()),
                ('trivia', models.TextField()),
                ('storyLine', models.TextField()),
                ('platform', models.CharField(max_length=120)),
                ('category', models.TextField(max_length=120)),
                ('releaseDate', models.DateField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articalimage',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='age',
        ),
        migrations.AddField(
            model_name='articalimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cast',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='movie',
            name='releaseDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cast',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
