# Generated by Django 3.1.1 on 2020-10-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20201002_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='contentHeader',
        ),
        migrations.AddField(
            model_name='movie',
            name='contentHead',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
