# Generated by Django 3.1.1 on 2020-10-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20201002_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='contentHead',
            field=models.TextField(blank=True),
        ),
    ]
