# Generated by Django 3.1.1 on 2020-10-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20201002_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photos', models.ImageField(blank=True, upload_to='')),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('awards', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('movies', models.TextField()),
                ('socialMedia', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
