# Generated by Django 3.1.1 on 2020-10-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_cast_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='field',
        ),
        migrations.AddField(
            model_name='cast',
            name='fields',
            field=models.TextField(default='here'),
        ),
    ]
