# Generated by Django 3.1.1 on 2020-10-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20201002_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='fields',
        ),
    ]
