# Generated by Django 3.1.1 on 2020-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_remove_cast_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='field',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
