# Generated by Django 3.1.1 on 2020-10-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
