# Generated by Django 3.1.1 on 2020-10-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20201003_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='id',
        ),
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='NAME'),
        ),
    ]
