# Generated by Django 3.1.1 on 2020-10-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20201003_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
