# Generated by Django 3.1.1 on 2020-10-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20201003_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('content', models.TextField()),
            ],
        ),
    ]
