# Generated by Django 3.1.1 on 2020-10-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_expenses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.AlterField(
            model_name='cast',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poster',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
